---
version: "2.1"
services:
  syncthing:
    build: .
    environment:
      PUID: "0"
      PGID: "0"
    ports:
      - 80:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    privileged: true # required to mount usb storage
    volumes:
      - config:/config
      - data:/data

  hostname:
    build: hostname
    restart: no
    labels:
      io.balena.features.supervisor-api: 1
    environment:
      SET_HOSTNAME: syncthing

  restic:
    build: restic
    labels:
      io.balena.features.supervisor-api: 1
      io.balena.features.balena-socket: 1
    volumes:
      - restic:/cache

volumes:
  config: {}
  data: {}
  restic: {}
