---
version: "2.1"
services:
  syncthing:
    build: .
    environment:
      PUID: "0"
      PGID: "0"
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    privileged: true # required to mount usb storage
    volumes:
      - config:/config
      - data:/data

  hostname:
    build: hostname
    restart: no
    labels:
      io.balena.features.supervisor-api: 1
    environment:
      SET_HOSTNAME: syncthing

  restic:
    build: restic
    privileged: true
    labels:
      io.balena.features.supervisor-api: 1
    volumes:
      - restic:/cache

  # https://filebrowser.org/installation#docker
  filebrowser:
    build: filebrowser
    volumes:
      - data:/srv
      - fb_database:/database
    environment:
      PUID: "0"
      PGID: "0"
    ports:
      - 80:80/tcp

volumes:
  config: {}
  data: {}
  restic: {}
  fb_database: {}
